from __future__ import annotations

from typing import Any


AGENT_PROMPT_DEFINITIONS = (
    {
        "agent_code": "central_router_agent",
        "display_name": "中央路由 Agent",
        "prompt_text": (
            "你是 CRM 自动化转化中央路由 Agent。"
            "请先理解客户最新上下文，再判断应由哪个执行 Agent 接手，并输出清晰的路由决策。"
        ),
    },
    {
        "agent_code": "welcome_agent",
        "display_name": "欢迎接待 Agent",
        "prompt_text": (
            "你是 CRM 自动化转化欢迎接待 Agent。"
            "目标是在首次接触时快速建立关系、确认客户当前诉求，并生成自然的跟进建议。"
        ),
    },
    {
        "agent_code": "pricing_agent",
        "display_name": "价格答疑 Agent",
        "prompt_text": (
            "你是 CRM 自动化转化价格答疑 Agent。"
            "请围绕价格、套餐、支付方式、价值说明生成清晰且克制的回复建议。"
        ),
    },
    {
        "agent_code": "proof_agent",
        "display_name": "案例证明 Agent",
        "prompt_text": (
            "你是 CRM 自动化转化案例证明 Agent。"
            "请基于客户当前疑虑，生成更适合用于建立信任的案例、证据和证明性表达。"
        ),
    },
    {
        "agent_code": "closing_agent",
        "display_name": "成交推进 Agent",
        "prompt_text": (
            "你是 CRM 自动化转化成交推进 Agent。"
            "请在不夸张承诺的前提下，帮助推进下一步行动、预约、付款或明确成交条件。"
        ),
    },
)

AGENT_PROMPT_DEFINITION_MAP = {str(item["agent_code"]): dict(item) for item in AGENT_PROMPT_DEFINITIONS}
AGENT_PROMPT_ORDER = [str(item["agent_code"]) for item in AGENT_PROMPT_DEFINITIONS]

AGENT_OUTPUT_TYPE_OPTIONS = (
    "route_ingress_sent",
    "route_ingress_acked",
    "pending_callback_alert",
    "callback_received",
    "callback_validated",
    "callback_rejected",
    "route_decision",
    "agent_reply_draft",
    "agent_reply_final",
    "pool_change_suggestion",
    "pool_change_applied",
    "next_action_suggestion",
    "fallback_decision",
    "error_output",
)

ROUTER_REQUEST_SAMPLE = {
    "request_id": "route-req-20260410-001",
    "external_contact_id": "wm_agent_route_001",
    "recent_messages": [
        {"role": "customer", "content": "课程多少钱？", "created_at": "2026-04-10 09:15:00"},
        {"role": "staff", "content": "你更关注价格还是课程效果？", "created_at": "2026-04-10 09:15:21"},
    ],
}

ROUTER_ACK_SAMPLE = {
    "http_status": 200,
    "body": {"ok": True, "accepted": True},
}

ROUTER_RESPONSE_SAMPLE = {
    "request_id": "route-req-20260410-001",
    "external_contact_id": "wm_agent_route_001",
    "target_pool": "operating",
    "agent_code": "pricing_agent",
    "reason": "客户最后一轮持续追问价格与付费方式",
    "confidence": 0.86,
    "need_human_review": False,
    "next_action": "quote_explain",
    "reply_draft": "这边我先把课程方案和价格区间给你拆开说明，方便你快速判断哪种更适合你。",
    "completed_at": "2026-04-10 09:15:45",
}

ROUTER_FALLBACK_DEFAULT = {
    "on_timeout": "fallback_to_default_agent",
    "on_invalid_schema": "human_review_queue",
    "on_unknown_agent_code": "fallback_to_default_agent",
    "default_agent_code": "welcome_agent",
    "default_pool": "pending_questionnaire",
    "pending_callback_timeout_minutes": 10,
    "need_human_review": True,
    "alert_channel": "run_center",
    "fail_closed": True,
}


def _common_output_schema() -> list[dict[str, Any]]:
    return [
        {"field_key": "agent_code", "display_name": "Agent Code", "type": "string", "required": True, "description": "当前输出所属的子 Agent。", "example": "pricing_agent"},
        {"field_key": "userid", "display_name": "负责人", "type": "string", "required": False, "description": "执行上下文内的负责人或 owner。", "example": "sales_01"},
        {"field_key": "target_pool", "display_name": "目标池子", "type": "string", "required": False, "description": "如果输出建议改池，记录目标池子。", "example": "operating"},
        {"field_key": "confidence", "display_name": "置信度", "type": "number", "required": False, "description": "结构化结果的置信度。", "example": 0.82},
        {"field_key": "reason", "display_name": "原因", "type": "string", "required": True, "description": "解释为什么给出当前建议。", "example": "客户连续追问价格与成交条件。"},
        {"field_key": "next_action", "display_name": "下一步动作", "type": "string", "required": False, "description": "建议系统或运营下一步做什么。", "example": "send_pricing_clarification"},
        {"field_key": "draft_reply", "display_name": "草稿回复", "type": "string", "required": False, "description": "生成给客户的草稿回复。", "example": "目前课程有 2 档方案，我先给你拆开说明。"},
        {"field_key": "need_human_review", "display_name": "需要人工复核", "type": "boolean", "required": True, "description": "是否需要人工复核后再采用。", "example": False},
    ]


def _common_variables() -> list[dict[str, Any]]:
    return [
        {
            "variable_key": "recent_messages",
            "display_name": "近 20 条消息",
            "description": "客户最近消息上下文，用于理解当前对话意图。",
            "source": "archive.recent_messages",
            "example_value": ["客户：课程多少钱？", "员工：你更关注价格还是效果？"],
            "enabled": True,
            "required": True,
            "sort_order": 10,
        },
        {
            "variable_key": "current_pool",
            "display_name": "当前池子",
            "description": "成员当前所在池子。",
            "source": "automation_member.current_pool",
            "example_value": "operating",
            "enabled": True,
            "required": True,
            "sort_order": 20,
        },
        {
            "variable_key": "current_stage",
            "display_name": "当前阶段",
            "description": "成员当前阶段标识。",
            "source": "automation_member.current_stage",
            "example_value": "operating_followup",
            "enabled": True,
            "required": True,
            "sort_order": 30,
        },
        {
            "variable_key": "focus_reason",
            "display_name": "重点原因",
            "description": "如果当前是重点跟进，说明命中原因或人工改判原因。",
            "source": "automation_member.decision_source + questionnaire",
            "example_value": "命中关键题：预算与落地周期",
            "enabled": True,
            "required": False,
            "sort_order": 40,
        },
        {
            "variable_key": "owner_name",
            "display_name": "负责人",
            "description": "当前成员负责人展示名。",
            "source": "customer_profile.owner_display_name",
            "example_value": "HuangYouCan",
            "enabled": True,
            "required": False,
            "sort_order": 60,
        },
        {
            "variable_key": "last_touch_at",
            "display_name": "最近触达时间",
            "description": "最近人工或系统触达时间。",
            "source": "automation_event / member.updated_at",
            "example_value": "2026-04-10 09:00:00",
            "enabled": True,
            "required": False,
            "sort_order": 70,
        },
        {
            "variable_key": "member_tags",
            "display_name": "成员标签",
            "description": "来自营销画像或 CRM 的标签集合。",
            "source": "marketing_profile.tags",
            "example_value": ["价格敏感", "已问课程安排"],
            "enabled": True,
            "required": False,
            "sort_order": 80,
        },
        {
            "variable_key": "current_audience_code",
            "display_name": "当前大人群",
            "description": "成员当前所在自动化转化大人群。",
            "source": "automation_member.current_audience_code",
            "example_value": "operating",
            "enabled": True,
            "required": False,
            "sort_order": 90,
        },
        {
            "variable_key": "latest_agent_outputs",
            "display_name": "最近 Agent 输出",
            "description": "同一成员最近的 Agent 输出摘要。",
            "source": "agent_output_ledger",
            "example_value": ["pricing_agent: 价格异议解释", "closing_agent: 建议预约试听"],
            "enabled": True,
            "required": False,
            "sort_order": 100,
        },
    ]


CHILD_AGENT_CONFIG_DEFINITIONS = (
    {
        "agent_code": "welcome_agent",
        "display_name": "欢迎接待 Agent",
        "pool_keys": ["pending_questionnaire"],
        "role_prompt": "你是自动化转化里的欢迎接待 Agent，职责是在首次对话中建立关系、识别意图，并避免过度销售。",
        "task_prompt": "基于最近消息和成员上下文，输出一条适合首次接待的跟进建议与草稿回复；如果信息不足，明确说明缺口并保持克制。",
        "variables": _common_variables(),
        "output_schema": _common_output_schema(),
    },
    {
        "agent_code": "pricing_agent",
        "display_name": "价格答疑 Agent",
        "pool_keys": ["operating"],
        "role_prompt": "你是自动化转化里的价格答疑 Agent，负责围绕价格、价值、支付与方案选择给出清晰说明，不夸大承诺。",
        "task_prompt": "识别客户当前的价格疑问，输出结构化判断、建议池子/下一步动作和一段可发送的价格解释草稿。",
        "variables": _common_variables(),
        "output_schema": _common_output_schema(),
    },
    {
        "agent_code": "proof_agent",
        "display_name": "案例证明 Agent",
        "pool_keys": ["operating"],
        "role_prompt": "你是自动化转化里的案例证明 Agent，职责是补充案例、证据和可信背书，帮助客户建立信任。",
        "task_prompt": "结合当前阶段和客户疑虑，生成证据型跟进建议，输出理由、下一步动作和一段案例说明草稿。",
        "variables": _common_variables(),
        "output_schema": _common_output_schema(),
    },
    {
        "agent_code": "closing_agent",
        "display_name": "成交推进 Agent",
        "pool_keys": ["operating", "converted"],
        "role_prompt": "你是自动化转化里的成交推进 Agent，职责是推进预约、付款、确认下一步，但不能替代人工做高风险承诺。",
        "task_prompt": "基于最近上下文输出成交推进建议，必要时提示人工复核，并返回结构化 next_action 与 draft_reply。",
        "variables": _common_variables(),
        "output_schema": _common_output_schema(),
    },
)

CHILD_AGENT_CONFIG_MAP = {str(item["agent_code"]): dict(item) for item in CHILD_AGENT_CONFIG_DEFINITIONS}
CHILD_AGENT_ORDER = [str(item["agent_code"]) for item in CHILD_AGENT_CONFIG_DEFINITIONS]

_CRM_SKILL_POOL_KEYS = [
    "pending_questionnaire",
    "operating",
    "converted",
    "no_reply",
    "human_reply",
]

SKILL_REGISTRY_DEFINITIONS = (
    {
        "skill_code": "crm.get_member_basic",
        "agent_code": "shared",
        "pool_keys": list(_CRM_SKILL_POOL_KEYS),
        "read_capabilities": ["member_basic"],
        "write_capabilities": [],
        "enabled": True,
        "input_schema": {"external_contact_id": "string", "phone": "string"},
        "output_schema": {"member_exists": "boolean", "basic": "object"},
        "permission_notes": "只读查询成员基础信息；默认走内部 MCP 审计。",
        "idempotency_notes": "纯读取，无需幂等键。",
        "audit_notes": "记录 external_contact_id / phone 与返回状态。",
        "example_request": {"external_contact_id": "wm_agent_route_001"},
        "example_response": {"member_exists": True, "basic": {"customer_name": "李老师"}},
    },
    {
        "skill_code": "crm.get_member_stage",
        "agent_code": "shared",
        "pool_keys": list(_CRM_SKILL_POOL_KEYS),
        "read_capabilities": ["member_stage", "pool_status"],
        "write_capabilities": [],
        "enabled": True,
        "input_schema": {"external_contact_id": "string", "phone": "string"},
        "output_schema": {"member_exists": "boolean", "stage": "object"},
        "permission_notes": "只读查询成员阶段、池子与跟进状态。",
        "idempotency_notes": "纯读取，无需幂等键。",
        "audit_notes": "记录调用来源与阶段结果。",
        "example_request": {"external_contact_id": "wm_agent_route_001"},
        "example_response": {"member_exists": True, "stage": {"current_pool": "operating"}},
    },
    {
        "skill_code": "crm.get_member_questionnaire",
        "agent_code": "shared",
        "pool_keys": list(_CRM_SKILL_POOL_KEYS),
        "read_capabilities": ["questionnaire_status", "questionnaire_matches"],
        "write_capabilities": [],
        "enabled": True,
        "input_schema": {"external_contact_id": "string", "phone": "string"},
        "output_schema": {"member_exists": "boolean", "questionnaire": "object"},
        "permission_notes": "只读查询问卷状态和命中题目。",
        "idempotency_notes": "纯读取，无需幂等键。",
        "audit_notes": "记录问卷读取来源。",
        "example_request": {"external_contact_id": "wm_agent_route_001"},
        "example_response": {"member_exists": True, "questionnaire": {"status": "submitted", "matched_questions": ["预算"]}},
    },
    {
        "skill_code": "crm.get_member_recent_events",
        "agent_code": "shared",
        "pool_keys": list(_CRM_SKILL_POOL_KEYS),
        "read_capabilities": ["timeline_events"],
        "write_capabilities": [],
        "enabled": True,
        "input_schema": {"external_contact_id": "string", "phone": "string", "limit": "integer<=100"},
        "output_schema": {"events": "array", "total": "integer"},
        "permission_notes": "只读查询最近事件摘要，不直接暴露额外系统写能力。",
        "idempotency_notes": "纯读取，无需幂等键。",
        "audit_notes": "记录事件读取数量与条件。",
        "example_request": {"external_contact_id": "wm_agent_route_001", "limit": 10},
        "example_response": {"events": [{"event_type": "questionnaire_submitted"}], "total": 12},
    },
    {
        "skill_code": "crm.get_member_recent_outputs",
        "agent_code": "shared",
        "pool_keys": list(_CRM_SKILL_POOL_KEYS),
        "read_capabilities": ["agent_output_history"],
        "write_capabilities": [],
        "enabled": True,
        "input_schema": {"external_contact_id": "string", "phone": "string", "limit": "integer<=100"},
        "output_schema": {"rows": "array", "total": "integer"},
        "permission_notes": "读取最近 Agent 输出，默认遵守现有脱敏策略。",
        "idempotency_notes": "纯读取，无需幂等键。",
        "audit_notes": "记录 output ledger 查询条件。",
        "example_request": {"external_contact_id": "wm_agent_route_001", "limit": 5},
        "example_response": {"rows": [{"output_type": "agent_reply_draft"}], "total": 2},
    },
    {
        "skill_code": "crm.get_member_snapshot",
        "agent_code": "shared",
        "pool_keys": list(_CRM_SKILL_POOL_KEYS),
        "read_capabilities": ["member_basic", "member_stage", "questionnaire_status"],
        "write_capabilities": [],
        "enabled": True,
        "input_schema": {"external_contact_id": "string", "phone": "string"},
        "output_schema": {"member_exists": "boolean", "basic": "object", "stage": "object", "questionnaire": "object"},
        "permission_notes": "聚合快照查询，便于 Lobster 通过 MCP 主动拉取 CRM 信息。",
        "idempotency_notes": "纯读取，无需幂等键。",
        "audit_notes": "记录聚合快照读取来源。",
        "example_request": {"external_contact_id": "wm_agent_route_001"},
        "example_response": {"member_exists": True, "stage": {"current_stage": "operating_followup"}},
    },
    {
        "skill_code": "script.list_items",
        "agent_code": "shared",
        "pool_keys": [],
        "read_capabilities": ["script_catalog"],
        "write_capabilities": [],
        "enabled": True,
        "input_schema": {"query": "string"},
        "output_schema": {"rows": "array", "total": "integer"},
        "permission_notes": "只读查看话术项列表与版本摘要。",
        "idempotency_notes": "纯读取，无需幂等键。",
        "audit_notes": "记录检索关键词与结果数。",
        "example_request": {"query": "pricing"},
        "example_response": {"rows": [{"agent_code": "pricing_agent"}], "total": 1},
    },
    {
        "skill_code": "script.get_item",
        "agent_code": "shared",
        "pool_keys": [],
        "read_capabilities": ["script_detail", "draft_and_published_versions"],
        "write_capabilities": [],
        "enabled": True,
        "input_schema": {"agent_code": "string"},
        "output_schema": {"item": "object"},
        "permission_notes": "读取单个子 Agent 的话术配置详情。",
        "idempotency_notes": "纯读取，无需幂等键。",
        "audit_notes": "记录 agent_code 与返回状态。",
        "example_request": {"agent_code": "pricing_agent"},
        "example_response": {"item": {"agent_code": "pricing_agent", "draft_version": 2}},
    },
    {
        "skill_code": "script.search_items",
        "agent_code": "shared",
        "pool_keys": [],
        "read_capabilities": ["script_catalog_search"],
        "write_capabilities": [],
        "enabled": True,
        "input_schema": {"keyword": "string"},
        "output_schema": {"rows": "array", "total": "integer"},
        "permission_notes": "按关键词检索话术项。",
        "idempotency_notes": "纯读取，无需幂等键。",
        "audit_notes": "记录关键词检索来源。",
        "example_request": {"keyword": "closing"},
        "example_response": {"rows": [{"agent_code": "closing_agent"}], "total": 1},
    },
    {
        "skill_code": "script.create_draft",
        "agent_code": "shared",
        "pool_keys": [],
        "read_capabilities": [],
        "write_capabilities": ["draft_prompt", "draft_variables", "draft_output_schema"],
        "enabled": True,
        "input_schema": {"agent_code": "string", "from_version": "published|draft", "operator": "string"},
        "output_schema": {"created": "boolean", "agent": "object"},
        "permission_notes": "只创建或刷新草稿，不直接发布。",
        "idempotency_notes": "建议调用方自行带幂等语义；当前按最新草稿覆盖。",
        "audit_notes": "记录草稿来源与操作人。",
        "example_request": {"agent_code": "pricing_agent", "from_version": "published", "operator": "lobster"},
        "example_response": {"created": True, "agent": {"draft_version": 2}},
    },
    {
        "skill_code": "script.update_draft",
        "agent_code": "shared",
        "pool_keys": [],
        "read_capabilities": [],
        "write_capabilities": ["draft_prompt", "draft_variables", "draft_output_schema"],
        "enabled": True,
        "input_schema": {"agent_code": "string", "role_prompt": "string", "task_prompt": "string", "operator": "string"},
        "output_schema": {"updated": "boolean", "agent": "object"},
        "permission_notes": "仅更新草稿态，不会直接生效。",
        "idempotency_notes": "建议按调用方版本或 request_id 做幂等。",
        "audit_notes": "记录具体修改来源。",
        "example_request": {"agent_code": "pricing_agent", "task_prompt": "更新报价说明", "operator": "lobster"},
        "example_response": {"updated": True, "agent": {"draft_version": 3}},
    },
    {
        "skill_code": "script.diff_draft",
        "agent_code": "shared",
        "pool_keys": [],
        "read_capabilities": ["draft_published_diff"],
        "write_capabilities": [],
        "enabled": True,
        "input_schema": {"agent_code": "string"},
        "output_schema": {"diff_summary": "array", "fields": "object"},
        "permission_notes": "只读比较草稿与已发布版本。",
        "idempotency_notes": "纯读取，无需幂等键。",
        "audit_notes": "记录 diff 查询结果。",
        "example_request": {"agent_code": "pricing_agent"},
        "example_response": {"diff_summary": ["任务提示词草稿尚未发布"]},
    },
    {
        "skill_code": "script.submit_for_publish",
        "agent_code": "shared",
        "pool_keys": [],
        "read_capabilities": [],
        "write_capabilities": ["publish_request"],
        "enabled": True,
        "input_schema": {"agent_code": "string", "operator": "string"},
        "output_schema": {"submitted": "boolean", "status": "string"},
        "permission_notes": "当前仅提交人工发布申请，不直接执行正式发布。",
        "idempotency_notes": "重复提交会覆盖最近一次申请摘要。",
        "audit_notes": "记录提交人、时间和草稿版本。",
        "example_request": {"agent_code": "pricing_agent", "operator": "lobster"},
        "example_response": {"submitted": True, "status": "pending_manual_publish"},
    },
    {
        "skill_code": "script.list_drafts",
        "agent_code": "shared",
        "pool_keys": [],
        "read_capabilities": ["draft_catalog"],
        "write_capabilities": [],
        "enabled": True,
        "input_schema": {"changed_only": "boolean"},
        "output_schema": {"rows": "array", "total": "integer"},
        "permission_notes": "查看当前所有草稿或仅看未发布变更。",
        "idempotency_notes": "纯读取，无需幂等键。",
        "audit_notes": "记录 changed_only 条件。",
        "example_request": {"changed_only": True},
        "example_response": {"rows": [{"agent_code": "pricing_agent"}], "total": 1},
    },
    {
        "skill_code": "get_pool_snapshot",
        "agent_code": "shared",
        "pool_keys": list(_CRM_SKILL_POOL_KEYS),
        "read_capabilities": ["pool_member_counts", "sample_members", "stage_summary"],
        "write_capabilities": [],
        "enabled": True,
        "input_schema": {"pool_key": "string", "limit": "integer<=50"},
        "output_schema": {"pool_key": "string", "member_count": "integer", "sample_members": "array"},
        "permission_notes": "只读查询；不返回完整敏感消息原文。",
        "idempotency_notes": "纯读取，无需幂等键。",
        "audit_notes": "所有调用都记录 skill audit。",
        "example_request": {"pool_key": "operating", "limit": 10},
        "example_response": {"pool_key": "operating", "member_count": 28},
    },
    {
        "skill_code": "crm.automation.get_workflow_registry",
        "agent_code": "shared",
        "pool_keys": [],
        "read_capabilities": ["workflow_registry", "enum_catalog"],
        "write_capabilities": [],
        "enabled": True,
        "input_schema": {},
        "output_schema": {"audiences": "array", "generation_modes": "array", "node_trigger_modes": "array"},
        "permission_notes": "只读查看任务流配置可用枚举与注册表。",
        "idempotency_notes": "纯读取，无需幂等键。",
        "audit_notes": "记录任务流注册表读取来源。",
        "example_request": {},
        "example_response": {"audiences": [{"value": "operating"}], "generation_modes": [{"value": "manual_layered"}]},
    },
    {
        "skill_code": "crm.automation.list_workflows",
        "agent_code": "shared",
        "pool_keys": [],
        "read_capabilities": ["workflow_catalog", "workflow_nodes"],
        "write_capabilities": [],
        "enabled": True,
        "input_schema": {"include_archived": "boolean", "status": "draft|active|paused"},
        "output_schema": {"items": "array", "total": "integer"},
        "permission_notes": "只读查看任务流列表；返回每个任务流的节点摘要。",
        "idempotency_notes": "纯读取，无需幂等键。",
        "audit_notes": "记录 status 与 include_archived 条件。",
        "example_request": {"status": "draft"},
        "example_response": {"total": 1, "items": [{"workflow": {"workflow_code": "welcome_flow"}, "nodes": []}]},
    },
    {
        "skill_code": "crm.automation.get_workflow_nodes",
        "agent_code": "shared",
        "pool_keys": [],
        "read_capabilities": ["workflow_nodes"],
        "write_capabilities": [],
        "enabled": True,
        "input_schema": {"workflow_id": "integer"},
        "output_schema": {"items": "array", "total": "integer"},
        "permission_notes": "只读查看单个任务流下全部节点。",
        "idempotency_notes": "纯读取，无需幂等键。",
        "audit_notes": "记录 workflow_id 与节点数。",
        "example_request": {"workflow_id": 12},
        "example_response": {"total": 2, "items": [{"node_code": "welcome_day_1"}]},
    },
    {
        "skill_code": "crm.automation.create_workflow",
        "agent_code": "shared",
        "pool_keys": [],
        "read_capabilities": [],
        "write_capabilities": ["workflow_create"],
        "enabled": True,
        "input_schema": {
            "workflow_name": "string",
            "workflow_code": "string",
            "audiences": "array",
            "status": "draft|active|paused",
            "recipient_filter_basis": "none|behavior",
            "recipient_behavior_tier_keys": "lt_2|between_2_9|gte_10[]",
            "content_segmentation_basis": "none|profile|behavior",
            "content_profile_segment_template_id": "integer",
            "segmentation_basis": "none|profile|behavior (legacy content syntax)",
            "generation_mode": "manual_layered|auto_layered_rewrite|personalized_single",
        },
        "output_schema": {"workflow_bundle": "object"},
        "permission_notes": "创建任务流草稿；不做自动发布审核绕过。",
        "idempotency_notes": "建议调用方传稳定 workflow_code，并通过业务侧避免重复创建。",
        "audit_notes": "记录 workflow_code、operator 和创建结果。发给谁与怎么发按独立维度记录。",
        "example_request": {
            "workflow_name": "新客欢迎流",
            "workflow_code": "welcome_flow",
            "audiences": ["operating"],
            "recipient_filter_basis": "none",
            "content_segmentation_basis": "none",
        },
        "example_response": {"workflow_bundle": {"workflow": {"workflow_code": "welcome_flow"}}},
    },
    {
        "skill_code": "crm.automation.create_workflow_node",
        "agent_code": "shared",
        "pool_keys": [],
        "read_capabilities": [],
        "write_capabilities": ["workflow_node_create"],
        "enabled": True,
        "input_schema": {"workflow_id": "integer", "node_name": "string", "target_audience_code": "string"},
        "output_schema": {"node": "object"},
        "permission_notes": "仅新增节点；要求目标人群属于对应任务流。",
        "idempotency_notes": "建议调用方自行避免同一 workflow_id 下重复 node_code。",
        "audit_notes": "记录 workflow_id、node_code、operator 和创建结果。",
        "example_request": {"workflow_id": 12, "node_name": "欢迎首触达", "target_audience_code": "operating"},
        "example_response": {"node": {"node_code": "welcome_touch_1", "target_audience_code": "operating"}},
    },
    {
        "skill_code": "list_agent_configs",
        "agent_code": "shared",
        "pool_keys": [],
        "read_capabilities": ["child_agent_catalog", "draft_version", "published_version"],
        "write_capabilities": [],
        "enabled": True,
        "input_schema": {"enabled_only": "boolean", "request_id": "string", "operator": "string", "idempotency_key": "string"},
        "output_schema": {"items": "array", "total": "integer"},
        "permission_notes": "只返回 child agents，不包含中央 router webhook 配置。",
        "idempotency_notes": "纯读取，无需幂等键。",
        "audit_notes": "记录 request_id、operator 和筛选条件。",
        "example_request": {"enabled_only": True, "request_id": "req-list-prompts-001"},
        "example_response": {"total": 4, "items": [{"agent_code": "pricing_agent"}]},
    },
    {
        "skill_code": "get_agent_config",
        "agent_code": "shared",
        "pool_keys": [],
        "read_capabilities": ["draft_version", "published_version", "enabled_context_sources", "draft_reply_output"],
        "write_capabilities": [],
        "enabled": True,
        "input_schema": {"agent_code": "string", "request_id": "string", "operator": "string", "idempotency_key": "string"},
        "output_schema": {"total": "integer", "items": "array", "bundle_version": "string", "bundle_hash": "string", "generated_at": "string"},
        "permission_notes": "只读查询配置，不返回 secret 明文。",
        "idempotency_notes": "纯读取，无需幂等键。",
        "audit_notes": "记录来源、operator 与访问结果。",
        "example_request": {"agent_code": "pricing_agent"},
        "example_response": {"total": 4, "bundle_version": "bundle-abcd1234", "bundle_hash": "sha256...", "items": [{"agent_code": "pricing_agent", "draft_version": 2}]},
    },
    {
        "skill_code": "create_agent_config",
        "agent_code": "shared",
        "pool_keys": [],
        "read_capabilities": [],
        "write_capabilities": ["create_agent", "draft_prompt", "enabled_context_sources"],
        "enabled": True,
        "input_schema": {
            "agent_code": "string",
            "display_name": "string",
            "enabled": "boolean",
            "role_prompt": "string",
            "task_prompt": "string",
            "enabled_context_sources": "array",
            "variables": "array",
            "output_schema": "array",
            "change_summary": "string",
            "operator": "string",
            "idempotency_key": "string",
        },
        "output_schema": {"created": "boolean", "agent": "object"},
        "permission_notes": "创建新的 child agent 草稿，不会自动发布到线上执行。推荐直接使用 enabled_context_sources，而不是手写 variables / output_schema。",
        "idempotency_notes": "建议调用方使用稳定 agent_code，并携带 idempotency_key 防止重复创建。",
        "audit_notes": "记录新建 agent 的编码、操作人和草稿摘要。",
        "example_request": {
            "agent_code": "questionnaire_followup_agent",
            "display_name": "问卷跟进 Agent",
            "role_prompt": "你是问卷跟进 Agent。",
            "task_prompt": "请基于 {{问卷信息}} 和 {{用户标签}} 生成首轮跟进话术。",
            "enabled_context_sources": ["questionnaire", "user_tags"],
            "operator": "lobster",
        },
        "example_response": {"created": True, "agent": {"agent_code": "questionnaire_followup_agent", "draft_version": 1}},
    },
    {
        "skill_code": "get_all_agent_prompts",
        "agent_code": "shared",
        "pool_keys": [],
        "read_capabilities": ["all_role_prompts", "all_task_prompts", "all_enabled_context_sources"],
        "write_capabilities": [],
        "enabled": True,
        "input_schema": {"enabled_only": "boolean", "request_id": "string", "operator": "string", "idempotency_key": "string"},
        "output_schema": {"items": "array", "total": "integer", "bundle_version": "string", "bundle_hash": "string", "generated_at": "string"},
        "permission_notes": "一次读取全部 child agent 提示词配置，不含中央 router。",
        "idempotency_notes": "纯读取，无需幂等键。",
        "audit_notes": "记录 request_id 和是否只看启用项。",
        "example_request": {"enabled_only": True, "request_id": "req-all-prompts-001"},
        "example_response": {"total": 4, "bundle_version": "bundle-abcd1234", "bundle_hash": "sha256...", "generated_at": "2026-04-12 10:00:00", "items": [{"agent_code": "pricing_agent", "draft": {"role_prompt": "..."}}]},
    },
    {
        "skill_code": "save_agent_prompt_draft",
        "agent_code": "shared",
        "pool_keys": [],
        "read_capabilities": [],
        "write_capabilities": ["draft_prompt", "enabled_context_sources"],
        "enabled": True,
        "input_schema": {"agent_code": "string", "patch": "object", "role_prompt": "string", "task_prompt": "string", "enabled_context_sources": "array", "variables": "array", "output_schema": "array", "expected_draft_version": "integer", "request_id": "string", "operator": "string", "change_summary": "string", "idempotency_key": "string"},
        "output_schema": {"agent_code": "string", "draft_version": "integer", "updated_at": "string"},
        "permission_notes": "只允许写草稿，不直接发布。推荐优先 patch enabled_context_sources，而不是手写 variables / output_schema。",
        "idempotency_notes": "建议携带 idempotency_key；支持字段级 partial patch，不要求全量覆盖；如携带 expected_draft_version 会启用乐观锁。",
        "audit_notes": "记录 request_id、operator、变更摘要、幂等键，以及版本冲突错误。",
        "example_request": {"agent_code": "pricing_agent", "task_prompt": "请结合 {{最近20条聊天信息}} 和 {{阶段信息}} 输出一条价格答疑话术。", "enabled_context_sources": ["recent_messages", "activation_info"], "expected_draft_version": 3, "change_summary": "收紧价格话术", "idempotency_key": "draft-001"},
        "example_response": {"agent_code": "pricing_agent", "draft_version": 3},
    },
    {
        "skill_code": "diff_agent_prompt",
        "agent_code": "shared",
        "pool_keys": [],
        "read_capabilities": ["draft_vs_published_diff"],
        "write_capabilities": [],
        "enabled": True,
        "input_schema": {"agent_code": "string", "request_id": "string", "operator": "string", "idempotency_key": "string"},
        "output_schema": {"fields": "object", "diff_summary": "array", "draft": "object", "published": "object"},
        "permission_notes": "只读查看草稿与已发布差异。",
        "idempotency_notes": "纯读取，无需幂等键。",
        "audit_notes": "记录 agent_code 与 request_id。",
        "example_request": {"agent_code": "pricing_agent", "request_id": "req-diff-001"},
        "example_response": {"fields": {"task_prompt_changed": True}, "diff_summary": ["任务提示词草稿尚未发布"]},
    },
    {
        "skill_code": "submit_agent_prompt_for_publish",
        "agent_code": "shared",
        "pool_keys": [],
        "read_capabilities": [],
        "write_capabilities": ["submit_draft_for_manual_publish"],
        "enabled": True,
        "input_schema": {"agent_code": "string", "change_summary": "string", "expected_draft_version": "integer", "request_id": "string", "operator": "string", "idempotency_key": "string"},
        "output_schema": {"submitted": "boolean", "status": "string", "agent": "object"},
        "permission_notes": "只提交人工发布申请，不直接正式发布。",
        "idempotency_notes": "建议携带 idempotency_key；可选 expected_draft_version 用于提交前并发保护。",
        "audit_notes": "记录 request_id、operator、变更摘要、提交结果和版本冲突。",
        "example_request": {"agent_code": "pricing_agent", "change_summary": "提交价格话术草稿审阅", "expected_draft_version": 3, "request_id": "req-submit-001"},
        "example_response": {"submitted": True, "status": "pending_manual_publish"},
    },
    {
        "skill_code": "list_pending_agent_prompt_publish_requests",
        "agent_code": "shared",
        "pool_keys": [],
        "read_capabilities": ["pending_publish_queue", "draft_versions", "submitted_metadata"],
        "write_capabilities": [],
        "enabled": True,
        "input_schema": {"agent_code": "string", "enabled_only": "boolean", "page": "integer", "page_size": "integer<=100", "request_id": "string", "operator": "string", "idempotency_key": "string"},
        "output_schema": {"total": "integer", "items": "array"},
        "permission_notes": "只读查看当前待发布申请与未发布改动。",
        "idempotency_notes": "纯读取，无需幂等键。",
        "audit_notes": "记录 request_id、operator 和筛选条件。",
        "example_request": {"enabled_only": True, "page": 1, "page_size": 20, "request_id": "req-pending-publish-001"},
        "example_response": {"total": 2, "items": [{"agent_code": "pricing_agent", "submitted_for_publish": True}]},
    },
    {
        "skill_code": "list_agent_outputs",
        "agent_code": "shared",
        "pool_keys": [],
        "read_capabilities": ["output_ledger", "filters", "pagination"],
        "write_capabilities": [],
        "enabled": True,
        "input_schema": {"filters": "object", "page": "integer", "page_size": "integer<=100"},
        "output_schema": {"rows": "array", "page": "integer", "total": "integer"},
        "permission_notes": "默认返回脱敏文本与结构化摘要。",
        "idempotency_notes": "纯读取，无需幂等键。",
        "audit_notes": "记录筛选条件和页码。",
        "example_request": {"filters": {"agent_code": "pricing_agent"}, "page": 1, "page_size": 20},
        "example_response": {"rows": [{"output_type": "agent_reply_draft"}], "total": 12},
    },
    {
        "skill_code": "get_agent_output",
        "agent_code": "shared",
        "pool_keys": [],
        "read_capabilities": ["output_detail", "run_context", "normalized_output"],
        "write_capabilities": [],
        "enabled": True,
        "input_schema": {"output_id": "string"},
        "output_schema": {"output": "object", "run": "object"},
        "permission_notes": "返回细节前会做敏感字段脱敏。",
        "idempotency_notes": "纯读取，无需幂等键。",
        "audit_notes": "记录 output_id 和调用来源。",
        "example_request": {"output_id": "aout-001"},
        "example_response": {"output": {"output_id": "aout-001"}, "run": {"run_id": "arun-001"}},
    },
    {
        "skill_code": "get_agent_outputs_by_request",
        "agent_code": "shared",
        "pool_keys": [],
        "read_capabilities": ["output_ledger", "request_lookup"],
        "write_capabilities": [],
        "enabled": True,
        "input_schema": {"request_id": "string"},
        "output_schema": {"rows": "array"},
        "permission_notes": "按 request_id 读取同一次执行下的全部输出。",
        "idempotency_notes": "纯读取，无需幂等键。",
        "audit_notes": "记录 request_id 和调用来源。",
        "example_request": {"request_id": "route-req-20260410-001"},
        "example_response": {"rows": [{"request_id": "route-req-20260410-001"}]},
    },
    {
        "skill_code": "get_agent_outputs_by_user",
        "agent_code": "shared",
        "pool_keys": [],
        "read_capabilities": ["output_ledger", "user_lookup"],
        "write_capabilities": [],
        "enabled": True,
        "input_schema": {"userid": "string", "limit": "integer<=100"},
        "output_schema": {"rows": "array"},
        "permission_notes": "按 external_contact_id / userid 查看最近输出。",
        "idempotency_notes": "纯读取，无需幂等键。",
        "audit_notes": "记录 userid 和 limit。",
        "example_request": {"userid": "wm_agent_route_001", "limit": 5},
        "example_response": {"rows": [{"userid": "wm_agent_route_001"}]},
    },
    {
        "skill_code": "export_agent_outputs",
        "agent_code": "shared",
        "pool_keys": [],
        "read_capabilities": ["export_job"],
        "write_capabilities": ["export_task"],
        "enabled": True,
        "input_schema": {"filters": "object", "requested_by": "string"},
        "output_schema": {"job": "object"},
        "permission_notes": "只允许创建导出任务，不直接暴露未脱敏原始文件内容。",
        "idempotency_notes": "建议按筛选条件生成 export job id。",
        "audit_notes": "导出任务创建与下载都要记录操作来源。",
        "example_request": {"filters": {"agent_code": "pricing_agent"}, "requested_by": "lobster"},
        "example_response": {"job": {"status": "queued"}},
    },
    {
        "skill_code": "suggest_pool_action",
        "agent_code": "shared",
        "pool_keys": ["pending_questionnaire", "operating", "converted"],
        "read_capabilities": ["member_detail", "stage_context"],
        "write_capabilities": [],
        "enabled": True,
        "input_schema": {"external_contact_id": "string", "phone": "string"},
        "output_schema": {"next_action": "string", "target_pool": "string", "reason": "string"},
        "permission_notes": "只给建议，不直接落库改池。",
        "idempotency_notes": "纯建议，无需幂等键。",
        "audit_notes": "建议结果会进入 Agent Output Ledger。",
        "example_request": {"external_contact_id": "wm_agent_route_001"},
        "example_response": {"next_action": "keep_followup", "target_pool": "operating"},
    },
)

SKILL_REGISTRY_MAP = {str(item["skill_code"]): dict(item) for item in SKILL_REGISTRY_DEFINITIONS}
SKILL_REGISTRY_ORDER = [str(item["skill_code"]) for item in SKILL_REGISTRY_DEFINITIONS]


def default_agent_prompt_payloads() -> list[dict[str, Any]]:
    return [
        {
            "agent_code": str(item["agent_code"]),
            "display_name": str(item["display_name"]),
            "prompt_text": str(item["prompt_text"]),
            "enabled": True,
            "version": 1,
        }
        for item in AGENT_PROMPT_DEFINITIONS
    ]


def default_agent_router_payload() -> dict[str, Any]:
    return {
        "enabled": False,
        "webhook_url": "",
        "signature_token": "",
        "signature_secret": "",
        "signature_header": "X-Lobster-Signature",
        "timeout_seconds": 8,
        "retry_count": 1,
        "fallback_strategy": dict(ROUTER_FALLBACK_DEFAULT),
        "request_sample": dict(ROUTER_REQUEST_SAMPLE),
        "response_sample": dict(ROUTER_RESPONSE_SAMPLE),
    }


def default_agent_config_payloads() -> list[dict[str, Any]]:
    payloads: list[dict[str, Any]] = []
    for item in CHILD_AGENT_CONFIG_DEFINITIONS:
        payloads.append(
            {
                "agent_code": str(item["agent_code"]),
                "display_name": str(item["display_name"]),
                "pool_keys": list(item.get("pool_keys") or []),
                "enabled": True,
                "draft_role_prompt": str(item["role_prompt"]),
                "draft_task_prompt": str(item["task_prompt"]),
                "draft_variables": list(item.get("variables") or []),
                "draft_output_schema": list(item.get("output_schema") or []),
                "published_role_prompt": str(item["role_prompt"]),
                "published_task_prompt": str(item["task_prompt"]),
                "published_variables": list(item.get("variables") or []),
                "published_output_schema": list(item.get("output_schema") or []),
                "draft_version": 1,
                "published_version": 1,
                "last_modified_source": "seed",
                "last_change_summary": "初始化默认 Agent 配置",
            }
        )
    return payloads


def default_skill_registry_payloads() -> list[dict[str, Any]]:
    payloads: list[dict[str, Any]] = []
    for item in SKILL_REGISTRY_DEFINITIONS:
        payloads.append(
            {
                "skill_code": str(item["skill_code"]),
                "agent_code": str(item["agent_code"]),
                "pool_keys": list(item.get("pool_keys") or []),
                "read_capabilities": list(item.get("read_capabilities") or []),
                "write_capabilities": list(item.get("write_capabilities") or []),
                "enabled": bool(item.get("enabled", True)),
                "input_schema": dict(item.get("input_schema") or {}),
                "output_schema": dict(item.get("output_schema") or {}),
                "permission_notes": str(item.get("permission_notes") or ""),
                "idempotency_notes": str(item.get("idempotency_notes") or ""),
                "audit_notes": str(item.get("audit_notes") or ""),
                "example_request": dict(item.get("example_request") or {}),
                "example_response": dict(item.get("example_response") or {}),
            }
        )
    return payloads
