from __future__ import annotations

from datetime import date
from pathlib import Path

import yaml

from scripts.ci.check_dependency_security import validate_dependency_security


ROOT = Path(__file__).resolve().parents[1]


def test_checked_in_dependency_lock_and_acceptance_are_valid() -> None:
    assert validate_dependency_security(today=date(2026, 7, 10)) == []


def test_dependency_lock_rejects_unhashed_entries(tmp_path: Path) -> None:
    lock = tmp_path / "requirements.lock"
    lock.write_text(
        """# This file is autogenerated by pip-compile with Python 3.10
# pip-compile --allow-unsafe --generate-hashes
demo==1.0
pip==26.1.2 \\
    --hash=sha256:382ff9f685ee3bc25864f820aa50505825f10f5458ffff07e30a6d96e5715cab
""",
        encoding="utf-8",
    )
    requirements = tmp_path / "requirements.txt"
    requirements.write_text("demo==1.0\n", encoding="utf-8")

    errors = validate_dependency_security(
        lock_path=lock,
        input_paths=(requirements,),
        acceptance_path=ROOT / "docs" / "security" / "dependency_risk_acceptance.yml",
        today=date(2026, 7, 10),
    )

    assert "locked dependency has no sha256 hash: demo" in errors


def test_dependency_acceptance_requires_complete_unexpired_metadata(tmp_path: Path) -> None:
    acceptance = yaml.safe_load(
        (ROOT / "docs" / "security" / "dependency_risk_acceptance.yml").read_text(encoding="utf-8")
    )
    acceptance["exceptions"] = [
        {
            "advisory_id": "GHSA-test",
            "ecosystem": "python",
            "package": "demo",
            "severity": "high",
            "owner": "security",
            "reason": "temporary upstream compatibility",
            "compensating_control": "feature remains disabled",
            "expires_at": "2026-07-09",
        }
    ]
    acceptance_path = tmp_path / "acceptance.yml"
    acceptance_path.write_text(yaml.safe_dump(acceptance, sort_keys=False), encoding="utf-8")

    errors = validate_dependency_security(
        acceptance_path=acceptance_path,
        today=date(2026, 7, 10),
    )

    assert "dependency exception[0] expired on 2026-07-09" in errors
