"""Identity and contact application skeleton for Wave 2."""

from .commands import (
    BindExternalContactIdentityCommand,
    MarkExternalContactFollowUserStatusCommand,
    MarkExternalContactIdentityStatusCommand,
    RefreshExternalContactIdentityOwnerCommand,
    ReplaceFollowUsersCommand,
    UpsertExternalContactIdentityCommand,
)
from .dto import (
    BindExternalContactIdentityCommandDTO,
    BindExternalContactIdentityResultDTO,
    CountExternalContactIdentityMapsQueryDTO,
    CountExternalContactIdentityMapsResultDTO,
    GetContactBindingStatusQueryDTO,
    GetContactBindingStatusResultDTO,
    GetPrimaryFollowUserUseridQueryDTO,
    GetPrimaryFollowUserUseridResultDTO,
    MarkExternalContactFollowUserStatusCommandDTO,
    MarkExternalContactFollowUserStatusResultDTO,
    MarkExternalContactIdentityStatusCommandDTO,
    MarkExternalContactIdentityStatusResultDTO,
    RefreshExternalContactIdentityOwnerCommandDTO,
    RefreshExternalContactIdentityOwnerResultDTO,
    ReplaceFollowUsersCommandDTO,
    ReplaceFollowUsersResultDTO,
    ResolveExternalContactIdentityQueryDTO,
    ResolveExternalContactIdentityResultDTO,
    ResolvePersonIdentityQueryDTO,
    ResolvePersonIdentityResultDTO,
    UpsertExternalContactIdentityCommandDTO,
    UpsertExternalContactIdentityResultDTO,
)
from .queries import (
    CountExternalContactIdentityMapsQuery,
    GetContactBindingStatusQuery,
    GetPrimaryFollowUserUseridQuery,
    ResolveExternalContactIdentityQuery,
    ResolvePersonIdentityQuery,
)

__all__ = [
    "BindExternalContactIdentityCommand",
    "BindExternalContactIdentityCommandDTO",
    "BindExternalContactIdentityResultDTO",
    "CountExternalContactIdentityMapsQuery",
    "CountExternalContactIdentityMapsQueryDTO",
    "CountExternalContactIdentityMapsResultDTO",
    "GetContactBindingStatusQuery",
    "GetContactBindingStatusQueryDTO",
    "GetContactBindingStatusResultDTO",
    "GetPrimaryFollowUserUseridQuery",
    "GetPrimaryFollowUserUseridQueryDTO",
    "GetPrimaryFollowUserUseridResultDTO",
    "MarkExternalContactFollowUserStatusCommand",
    "MarkExternalContactFollowUserStatusCommandDTO",
    "MarkExternalContactFollowUserStatusResultDTO",
    "MarkExternalContactIdentityStatusCommand",
    "MarkExternalContactIdentityStatusCommandDTO",
    "MarkExternalContactIdentityStatusResultDTO",
    "RefreshExternalContactIdentityOwnerCommand",
    "RefreshExternalContactIdentityOwnerCommandDTO",
    "RefreshExternalContactIdentityOwnerResultDTO",
    "ReplaceFollowUsersCommand",
    "ReplaceFollowUsersCommandDTO",
    "ReplaceFollowUsersResultDTO",
    "ResolveExternalContactIdentityQuery",
    "ResolveExternalContactIdentityQueryDTO",
    "ResolveExternalContactIdentityResultDTO",
    "ResolvePersonIdentityQuery",
    "ResolvePersonIdentityQueryDTO",
    "ResolvePersonIdentityResultDTO",
    "UpsertExternalContactIdentityCommand",
    "UpsertExternalContactIdentityCommandDTO",
    "UpsertExternalContactIdentityResultDTO",
]
