#!/usr/bin/env python3
from __future__ import annotations

import argparse
import re
from datetime import date
from pathlib import Path

import yaml
from packaging.requirements import Requirement
from packaging.utils import canonicalize_name
from packaging.version import Version


ROOT = Path(__file__).resolve().parents[2]
DEFAULT_LOCK = ROOT / "requirements.lock"
DEFAULT_INPUTS = (ROOT / "requirements.txt", ROOT / "requirements-dev.txt")
DEFAULT_ACCEPTANCE = ROOT / "docs" / "security" / "dependency_risk_acceptance.yml"
LOCK_ENTRY = re.compile(r"^(?P<name>[A-Za-z0-9_.-]+)==(?P<version>[^\s\\]+)(?:\s*\\)?$")
HASH = re.compile(r"--hash=sha256:[0-9a-f]{64}\b")
REQUIRED_EXCEPTION_FIELDS = {
    "advisory_id",
    "ecosystem",
    "package",
    "severity",
    "owner",
    "reason",
    "compensating_control",
    "expires_at",
}


def _lock_entries(path: Path) -> tuple[dict[str, tuple[str, int]], list[str]]:
    body = path.read_text(encoding="utf-8")
    errors: list[str] = []
    if "autogenerated by pip-compile with Python 3.10" not in body:
        errors.append("requirements.lock must be generated with Python 3.10")
    if "--allow-unsafe" not in body or "--generate-hashes" not in body:
        errors.append("requirements.lock header must include --allow-unsafe and --generate-hashes")
    entries: dict[str, tuple[str, int]] = {}
    current_name = ""
    current_hashes = 0
    for line in body.splitlines():
        if line and not line[0].isspace() and not line.startswith("#"):
            if current_name and current_hashes == 0:
                errors.append(f"locked dependency has no sha256 hash: {current_name}")
            match = LOCK_ENTRY.fullmatch(line)
            if not match:
                errors.append(f"unparseable lock entry: {line}")
                current_name = ""
                current_hashes = 0
                continue
            current_name = canonicalize_name(match.group("name"))
            current_hashes = 0
            if current_name in entries:
                errors.append(f"duplicate locked dependency: {current_name}")
            entries[current_name] = (match.group("version"), 0)
            continue
        if current_name:
            current_hashes += len(HASH.findall(line))
            version, _count = entries[current_name]
            entries[current_name] = (version, current_hashes)
    if current_name and current_hashes == 0:
        errors.append(f"locked dependency has no sha256 hash: {current_name}")
    if "pip" not in entries:
        errors.append("requirements.lock must pin pip for reproducible clean installs")
    return entries, errors


def _direct_requirements(paths: tuple[Path, ...]) -> list[Requirement]:
    requirements: list[Requirement] = []
    for path in paths:
        for raw_line in path.read_text(encoding="utf-8").splitlines():
            line = raw_line.strip()
            if not line or line.startswith(("#", "-r ", "--requirement ")):
                continue
            requirements.append(Requirement(line))
    return requirements


def validate_dependency_security(
    *,
    lock_path: Path = DEFAULT_LOCK,
    input_paths: tuple[Path, ...] = DEFAULT_INPUTS,
    acceptance_path: Path = DEFAULT_ACCEPTANCE,
    today: date | None = None,
) -> list[str]:
    entries, errors = _lock_entries(lock_path)
    for requirement in _direct_requirements(input_paths):
        name = canonicalize_name(requirement.name)
        if name not in entries:
            errors.append(f"direct dependency missing from lock: {name}")
            continue
        version = Version(entries[name][0])
        if requirement.specifier and version not in requirement.specifier:
            errors.append(f"locked dependency violates input constraint: {name}=={version}")

    acceptance = yaml.safe_load(acceptance_path.read_text(encoding="utf-8")) or {}
    if not isinstance(acceptance, dict):
        errors.append("dependency risk acceptance must be a mapping")
        return errors
    policy_fields = set((acceptance.get("policy") or {}).get("exception_required_fields") or [])
    if policy_fields != REQUIRED_EXCEPTION_FIELDS:
        errors.append("dependency exception policy fields do not match the enforced schema")
    current = today or date.today()
    exceptions = acceptance.get("exceptions") or []
    if not isinstance(exceptions, list):
        errors.append("dependency exceptions must be a list")
        return errors
    for index, item in enumerate(exceptions):
        label = f"dependency exception[{index}]"
        if not isinstance(item, dict):
            errors.append(f"{label} must be a mapping")
            continue
        missing = sorted(field for field in REQUIRED_EXCEPTION_FIELDS if not str(item.get(field) or "").strip())
        if missing:
            errors.append(f"{label} missing fields: {','.join(missing)}")
        try:
            expires_at = date.fromisoformat(str(item.get("expires_at") or ""))
        except ValueError:
            errors.append(f"{label} expires_at must be YYYY-MM-DD")
            continue
        if expires_at < current:
            errors.append(f"{label} expired on {expires_at.isoformat()}")
    return errors


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Validate hashed dependency lock and risk acceptance metadata.")
    parser.add_argument("--lock", type=Path, default=DEFAULT_LOCK)
    parser.add_argument("--acceptance", type=Path, default=DEFAULT_ACCEPTANCE)
    args = parser.parse_args(argv)
    errors = validate_dependency_security(lock_path=args.lock, acceptance_path=args.acceptance)
    if errors:
        for message in errors:
            print(message)
        return 1
    print("dependency lock and risk acceptance: ok")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
