"""Class user application skeleton for Wave 2."""

from .commands import (
    ApplyClassUserStatusChangeCommand,
    MigrateClassUserStatusFromContactTagsCommand,
    UpdateClassUserStatusSyncResultCommand,
)
from .dto import (
    ApplyClassUserStatusChangeCommandDTO,
    ApplyClassUserStatusChangeResultDTO,
    ExportClassUserManagementRecordsQueryDTO,
    ExportClassUserManagementRecordsResultDTO,
    GetClassUserSnapshotQueryDTO,
    GetClassUserSnapshotResultDTO,
    GetClassUserStatusCurrentQueryDTO,
    GetClassUserStatusCurrentResultDTO,
    GetClassUserStatusDefinitionQueryDTO,
    GetClassUserStatusDefinitionResultDTO,
    ListClassUserManagementRecordsQueryDTO,
    ListClassUserManagementRecordsResultDTO,
    ListClassUserStatusHistoryQueryDTO,
    ListClassUserStatusHistoryResultDTO,
    MigrateClassUserStatusFromContactTagsCommandDTO,
    MigrateClassUserStatusFromContactTagsResultDTO,
    UpdateClassUserStatusSyncResultCommandDTO,
    UpdateClassUserStatusSyncResultResultDTO,
)
from .queries import (
    ExportClassUserManagementRecordsQuery,
    GetClassUserSnapshotQuery,
    GetClassUserStatusCurrentQuery,
    GetClassUserStatusDefinitionQuery,
    ListClassUserManagementRecordsQuery,
    ListClassUserStatusHistoryQuery,
)

__all__ = [
    "ApplyClassUserStatusChangeCommand",
    "ApplyClassUserStatusChangeCommandDTO",
    "ApplyClassUserStatusChangeResultDTO",
    "ExportClassUserManagementRecordsQuery",
    "ExportClassUserManagementRecordsQueryDTO",
    "ExportClassUserManagementRecordsResultDTO",
    "GetClassUserSnapshotQuery",
    "GetClassUserSnapshotQueryDTO",
    "GetClassUserSnapshotResultDTO",
    "GetClassUserStatusCurrentQuery",
    "GetClassUserStatusCurrentQueryDTO",
    "GetClassUserStatusCurrentResultDTO",
    "GetClassUserStatusDefinitionQuery",
    "GetClassUserStatusDefinitionQueryDTO",
    "GetClassUserStatusDefinitionResultDTO",
    "ListClassUserManagementRecordsQuery",
    "ListClassUserManagementRecordsQueryDTO",
    "ListClassUserManagementRecordsResultDTO",
    "ListClassUserStatusHistoryQuery",
    "ListClassUserStatusHistoryQueryDTO",
    "ListClassUserStatusHistoryResultDTO",
    "MigrateClassUserStatusFromContactTagsCommand",
    "MigrateClassUserStatusFromContactTagsCommandDTO",
    "MigrateClassUserStatusFromContactTagsResultDTO",
    "UpdateClassUserStatusSyncResultCommand",
    "UpdateClassUserStatusSyncResultCommandDTO",
    "UpdateClassUserStatusSyncResultResultDTO",
]
