from __future__ import annotations

from typing import Any, Literal, Protocol


Json = dict[str, Any]
AdapterMode = Literal["fake", "disabled", "staging", "production"]

REQUIRED_AUTOMATION_ADAPTER_RESULT_FIELDS = (
    "ok",
    "adapter",
    "mode",
    "operation",
    "idempotency_key",
    "target",
    "result",
    "audit_id",
    "side_effect_executed",
    "error_code",
    "error_message",
)


class AutomationWriteGatewayContract(Protocol):
    def override_followup_type(self, *, member_id: str, followup_type: str, operator: str = "system", reason: str = "", external_userid: str = "", idempotency_key: str | None = None) -> Json: ...
    def confirm_conversion(self, *, member_id: str, operator: str = "system", reason: str = "", external_userid: str = "", idempotency_key: str | None = None) -> Json: ...
    def enter_silent(self, *, member_id: str, operator: str = "system", reason: str = "", external_userid: str = "", idempotency_key: str | None = None) -> Json: ...
    def exit_marketing(self, *, member_id: str, operator: str = "system", reason: str = "", external_userid: str = "", idempotency_key: str | None = None) -> Json: ...
    def build_write_preview(self, *, operation: str, member_id: str = "", external_userid: str = "", payload_summary: dict[str, Any] | None = None, idempotency_key: str | None = None) -> Json: ...
    def record_write_audit(self, *, operation: str, target: dict[str, Any], result: dict[str, Any] | None = None, error_code: str = "", idempotency_key: str | None = None) -> Json: ...


class AutomationActivationGatewayContract(Protocol):
    def receive_activation_event(self, *, activation_event_id: str = "", member_id: str = "", external_userid: str = "", mobile: str = "", source: str = "activation_webhook", idempotency_key: str | None = None) -> Json: ...
    def normalize_activation_payload(self, *, activation_event_id: str = "", payload: dict[str, Any] | None = None, idempotency_key: str | None = None) -> Json: ...
    def build_activation_preview(self, *, activation_event_id: str = "", member_id: str = "", external_userid: str = "", mobile: str = "", payload_summary: dict[str, Any] | None = None, idempotency_key: str | None = None) -> Json: ...
    def record_activation_audit(self, *, operation: str, target: dict[str, Any], result: dict[str, Any] | None = None, error_code: str = "", idempotency_key: str | None = None) -> Json: ...


class OpenClawWebhookAdapterContract(Protocol):
    def push_member_context(self, *, member_id: str, external_userid: str = "", openclaw_context_id: str = "", payload_summary: dict[str, Any] | None = None, idempotency_key: str | None = None) -> Json: ...
    def push_workflow_context(self, *, workflow_id: str, member_id: str = "", execution_id: str = "", openclaw_context_id: str = "", payload_summary: dict[str, Any] | None = None, idempotency_key: str | None = None) -> Json: ...
    def build_openclaw_payload_preview(self, *, member_id: str = "", workflow_id: str = "", openclaw_context_id: str = "", payload_summary: dict[str, Any] | None = None, idempotency_key: str | None = None) -> Json: ...
    def record_openclaw_audit(self, *, operation: str, target: dict[str, Any], result: dict[str, Any] | None = None, error_code: str = "", idempotency_key: str | None = None) -> Json: ...


class AutomationWorkflowRuntimeAdapterContract(Protocol):
    def enqueue_workflow_run(self, *, workflow_id: str, member_id: str = "", execution_id: str = "", program_id: str = "", idempotency_key: str | None = None) -> Json: ...
    def run_workflow_node(self, *, workflow_id: str, node_id: str, member_id: str = "", execution_id: str = "", idempotency_key: str | None = None) -> Json: ...
    def run_due_workflows(self, *, workflow_id: str = "", program_id: str = "", limit: int = 50, idempotency_key: str | None = None) -> Json: ...
    def build_workflow_runtime_preview(self, *, workflow_id: str = "", node_id: str = "", member_id: str = "", execution_id: str = "", payload_summary: dict[str, Any] | None = None, idempotency_key: str | None = None) -> Json: ...
    def record_workflow_runtime_audit(self, *, operation: str, target: dict[str, Any], result: dict[str, Any] | None = None, error_code: str = "", idempotency_key: str | None = None) -> Json: ...


class AutomationAgentRuntimeAdapterContract(Protocol):
    def run_agent_task(self, *, agent_task_id: str, member_id: str = "", workflow_id: str = "", execution_id: str = "", payload_summary: dict[str, Any] | None = None, idempotency_key: str | None = None) -> Json: ...
    def generate_agent_output(self, *, agent_task_id: str, member_id: str = "", workflow_id: str = "", execution_id: str = "", payload_summary: dict[str, Any] | None = None, idempotency_key: str | None = None) -> Json: ...
    def review_agent_output(self, *, agent_task_id: str, output_id: str = "", reviewer: str = "system", decision: str = "preview", idempotency_key: str | None = None) -> Json: ...
    def build_agent_runtime_preview(self, *, agent_task_id: str = "", member_id: str = "", workflow_id: str = "", execution_id: str = "", payload_summary: dict[str, Any] | None = None, idempotency_key: str | None = None) -> Json: ...
    def record_agent_runtime_audit(self, *, operation: str, target: dict[str, Any], result: dict[str, Any] | None = None, error_code: str = "", idempotency_key: str | None = None) -> Json: ...
