import { type WorkspaceEntityType, type WorkspaceFixture, type WorkspaceSelectionState } from "./workspace_fixture.js";
export type WorkspacePanelMode = "summary" | "detail" | "guardrail";
export type WorkspaceFilterValue = "all" | string;
export type WorkspaceCanvasLaneId = "plans" | "groups" | "nodes" | "executions" | "push_center" | "evidence";
export type WorkspaceCanvasSortMode = "default" | "status" | "entity_type" | "updated_or_created_time" | "blocked_first" | "action_required_first";
export type WorkspaceCanvasGroupMode = "entity_lane";
export type WorkspaceDensity = "compact" | "comfortable";
export type WorkspaceSelectionMode = "single" | "multi";
export type WorkspaceCopyPreviewFormat = "text" | "json";
export type WorkspaceCopyStatus = "idle" | "copied" | "copy_failed";
export type WorkspaceDraftSaveStatus = "idle" | "saving" | "saved" | "failed" | "conflict" | "archived";
export type WorkspaceDraftStatus = "not_saved" | "draft" | "ready_for_review" | "archived" | "rejected";
export type WorkspaceDraftReviewStatus = "idle" | "requesting" | "ready_for_review" | "failed" | "conflict" | "blocked";
export type WorkspaceGovernanceRequestStatus = "idle" | "requesting" | "requested" | "failed" | "conflict" | "blocked";
export type WorkspacePushCenterBridgeStatus = "idle" | "requesting" | "bridged" | "failed" | "conflict" | "blocked";
export interface WorkspaceGovernanceReviewView {
    review_id: string;
    draft_id: string;
    review_status: string;
    snapshot_hash: string;
    steps: {
        step_id: string;
        step_type: string;
        step_status: string;
        actor_metadata?: Record<string, unknown>;
        updated_at?: string;
    }[];
    allowlist_summary: {
        hash: string;
        count: number;
        source_reference_summary: Record<string, unknown>;
    };
    gray_window: {
        start_at: string;
        end_at: string;
        timezone: string;
        window_status: string;
    };
    approved: false;
    execution_status: "not_execution";
    push_center_job_created: false;
    external_effect_job_created: false;
    broadcast_job_created: false;
    internal_event_created: false;
    real_external_call: false;
    can_claim_pass_90_plus: false;
}
export interface WorkspacePushCenterBridgeView {
    review_id: string;
    draft_id: string;
    review_status: string;
    push_center_job_created: true;
    push_center_job_id: string;
    push_center_projection_id: string;
    push_center_status: "pending";
    execution_status: "push_center_pending_not_sent";
    external_effect_job_created: false;
    broadcast_job_created: false;
    internal_event_created: false;
    real_external_call: false;
    can_claim_pass_90_plus: false;
    idempotent_replay?: boolean;
}
export declare const WORKSPACE_CANVAS_LANE_IDS: WorkspaceCanvasLaneId[];
export declare const WORKSPACE_CANVAS_SORT_MODES: WorkspaceCanvasSortMode[];
export declare const WORKSPACE_CANVAS_GROUP_MODES: WorkspaceCanvasGroupMode[];
export type WorkspaceLaneCollapsedState = Record<WorkspaceCanvasLaneId, boolean>;
export type WorkspaceSelectedEntityIds = Record<WorkspaceEntityType, string[]>;
export interface WorkspaceSelectedEntityRef {
    entityType: WorkspaceEntityType;
    id: string;
}
export interface WorkspaceViewState {
    keyword: string;
    planStatusFilter: WorkspaceFilterValue;
    entityTypeFilter: "all" | WorkspaceEntityType;
    executionStatusFilter: WorkspaceFilterValue;
    pushCenterStatusFilter: WorkspaceFilterValue;
    selectedEntityType: WorkspaceEntityType;
    selectedEntityId: string;
    panelMode: WorkspacePanelMode;
    laneCollapsedState: WorkspaceLaneCollapsedState;
    canvasSortMode: WorkspaceCanvasSortMode;
    canvasGroupMode: WorkspaceCanvasGroupMode;
    visibleLaneIds: WorkspaceCanvasLaneId[];
    density: WorkspaceDensity;
    focusedCanvasLaneId: WorkspaceCanvasLaneId;
    focusedCanvasCardId: string;
    selectedEntityIds: WorkspaceSelectedEntityIds;
    activeSelectionMode: WorkspaceSelectionMode;
    lastSelectedEntity: WorkspaceSelectedEntityRef | null;
    previewBundleId: string;
    bulkGuardrailSummary: string[];
    copyPreviewVisible: boolean;
    copyPreviewFormat: WorkspaceCopyPreviewFormat;
    copyStatus: WorkspaceCopyStatus;
    copyStatusMessage: string;
    currentDraftId: string;
    currentDraftVersion: number;
    currentDraftSnapshotHash: string;
    currentDraftIdempotencyKey: string;
    currentDraftReviewIdempotencyKey: string;
    currentDraftStatus: WorkspaceDraftStatus;
    draftSaveStatus: WorkspaceDraftSaveStatus;
    draftSaveMessage: string;
    draftReviewStatus: WorkspaceDraftReviewStatus;
    draftReviewMessage: string;
    currentGovernanceReviewId: string;
    currentGovernanceStatus: string;
    currentGovernanceIdempotencyKey: string;
    currentGovernanceReview: WorkspaceGovernanceReviewView | null;
    governanceRequestStatus: WorkspaceGovernanceRequestStatus;
    governanceRequestMessage: string;
    currentPushCenterBridge: WorkspacePushCenterBridgeView | null;
    pushCenterBridgeStatus: WorkspacePushCenterBridgeStatus;
    pushCenterBridgeMessage: string;
    currentPushCenterBridgeIdempotencyKey: string;
}
export declare function createWorkspaceViewState(fixture: WorkspaceFixture): WorkspaceViewState;
export declare function selectEntityInViewState(viewState: WorkspaceViewState, selectedEntityType: WorkspaceEntityType, selectedEntityId: string): WorkspaceViewState;
export declare function updateWorkspaceViewState(viewState: WorkspaceViewState, updates: Partial<WorkspaceViewState>): WorkspaceViewState;
export declare function toggleWorkspaceCanvasLane(viewState: WorkspaceViewState, laneId: WorkspaceCanvasLaneId): WorkspaceViewState;
export declare function selectionFromViewState(fixture: WorkspaceFixture, viewState: WorkspaceViewState): WorkspaceSelectionState;
